Capstone/Capstone.WebUI/Controllers/AdminLocController.cs
using Capstone.Domain.Concrete;
using Capstone.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Capstone.Domain.Abstract;

namespace Capstone.WebUI.Controllers
{
    public class AdminLocController : Controller
    {
        BvLocationInterface lRepo;

        // The default constructor is called by the framework
        public AdminLocController()
        {
            lRepo = new BvLocationRepository();
        }

        // Use this for dependency injection
        public AdminLocController(BvLocationRepository iLoc)
        {
            lRepo = iLoc;
        }

        public ActionResult AdminLocIndex()
        {
            //need to get a list of all users
            var db = new CapstoneDbContext();
            List<BvLocation> locations = (from l in db.BvLocations
                                select l).ToList<BvLocation>();
            return View(locations);
        }

        public ActionResult EditLoc(int bvLocationId)
        {
            BvLocation l = lRepo.GetBvLocation(bvLocationId);
            return View(l);
        }
        [HttpPost]
        public ActionResult EditLoc(BvLocation l)
        {
            if (ModelState.IsValid)
            {
                lRepo.SaveBvLocation(l);
                TempData["message"] = string.Format("{0} has been saved", l.BvLocationId);
                return RedirectToAction("AdminLocIndex");
            }
            else
            {
                return View(l);
            }
        }
        public ViewResult CreateLoc()
        {
            return View("EditLoc", new BvLocation());
        }

        [HttpPost]
        public ActionResult DeleteLoc(int bvLocationId)
        {
            BvLocation deletedLoc = lRepo.DeleteBvLocation(bvLocationId);
            if (deletedLoc != null)
            {
                TempData["message"] = string.Format("{0} was deleted", deletedLoc.BvStoreNum);
            }
            return RedirectToAction("AdminLocIndex");
        }

    }
}

Capstone/Capstone.WebUI/Views/AdminLoc/AdminLocIndex.cshtml
@model IEnumerable<Capstone.Domain.Entities.BvLocation>

@{
    ViewBag.Title = "AdminLocIndex";
}

<h2>AdminLocIndex</h2>

<table>
    <tr>
        <th>Store Number</th>
        <th>Address</th>
        <th>City</th>
        <th>Zip</th>
        <th>Phone</th>
    </tr>
@foreach (var item in Model) {
    <tr>
        <td>@Html.ActionLink(item.BvStoreNum, "EditLoc", "AdminLoc", new { item.BvLocationId }, null)</td>
        <td>@Html.DisplayFor(modelItem => item.Address)</td>
        <td>@Html.DisplayFor(modelItem => item.City)</td>
        <td>@Html.DisplayFor(modelItem => item.Zip)</td>
        <td>@Html.DisplayFor(modelItem => item.Phone)</td>
        <td>
            @using (Html.BeginForm("DeleteLoc", "AdminLoc", new { item.BvLocationId }))
            {
               <input type ="submit" value ="Delete" />
            }
        </td>
    </tr>
}
</table>
<p>@Html.ActionLink("Add a new restaurant", "CreateLoc")</p>

Capstone/Capstone.WebUI/Views/AdminLoc/EditLoc.cshtml
@model Capstone.Domain.Entities.BvLocation

@{
    ViewBag.Title = "EditLoc";
}

<h2>EditLoc</h2>

<h2>Edit @Model.BvStoreNum</h2>

@using (Html.BeginForm("EditLoc", "AdminLoc"))
{
    @Html.EditorForModel()
   <!-- TODO:  figure out how to get BVLoc and list store num with ability to edit this for the user-->
    <input type ="submit" value ="Save" />
    @Html.ActionLink("Cancel and return to List", "AdminLocIndex")
}