Capstone/Capstone.WebUI/Controllers/AdminCharityController.cs
using Capstone.Domain.Concrete;
using Capstone.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Capstone.WebUI.Controllers
{
    public class AdminCharityController : Controller
    {
        CharityRepository charRepo;

        public AdminCharityController()
        {
            charRepo = new CharityRepository();
        }

        public ActionResult Index()
        {
            List<Charity> charities = charRepo.GetCharities().ToList<Charity>();

            return View(charities);
        }

        public ActionResult Create()
        {
            return View("Edit", new Charity());
        }

        public ActionResult Edit(int charityId)
        {
            // Get the correct charity
            Charity charity = charRepo.GetCharities().FirstOrDefault(ch => ch.CharityId == charityId);
            
            return View(charity);
        }

        [HttpPost]
        public ActionResult Edit(Charity charity)
        {
            if (ModelState.IsValid)
            {
                // Save the changes to the partnership night 
                charRepo.EditCharity(charity);
                TempData["message"] = string.Format("{0} has been saved", charity.Name);
                return RedirectToAction("Index");
            }
            else
            {
                // there is something wrong with the data values
                return View(charity);
            }
        }

        public ActionResult Delete(int charityId)
        {
            Charity deletedCharity = charRepo.DeleteCharity(charityId);
            if (deletedCharity != null)
            {
                TempData["message"] = string.Format("{0} was deleted",
                deletedCharity.Name);
            }
            return RedirectToAction("Index");
        }
    }
}

Capstone/Capstone.WebUI/Views/AdminCharity/Edit.cshtml
@model Capstone.Domain.Entities.Charity

@{
    ViewBag.Title = "Edit";
}

<h1>Edit @Model.Name</h1>

@using (Html.BeginForm("Edit", "AdminCharity")) {

    @Html.EditorForModel()
    <input type="submit" value="Save" />

    @Html.ActionLink("Cancel and return to List", "Index")
}

Capstone/Capstone.WebUI/Views/AdminCharity/Index.cshtml
@model IEnumerable<Capstone.Domain.Entities.Charity>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>@Html.DisplayNameFor(model => model.Name)</th>
        <th>@Html.DisplayNameFor(model => model.Address)</th>
        <th>@Html.DisplayNameFor(model => model.City)</th>
        <th>@Html.DisplayNameFor(model => model.Zip)</th>
        <th>@Html.DisplayNameFor(model => model.Phone)</th>
        <th>TaxId</th>
        <th>Type</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>@Html.ActionLink(item.Name, "Edit", new {item.CharityId})</td>
        <td>@Html.DisplayFor(modelItem => item.Address)</td>
        <td>@Html.DisplayFor(modelItem => item.City)</td>
        <td>@Html.DisplayFor(modelItem => item.Zip)</td>
        <td>@Html.DisplayFor(modelItem => item.Phone)</td>
        <td>@Html.DisplayFor(modelItem => item.FederalTaxId)</td>
        <td>@Html.DisplayFor(modelItem => item.TypeOfCharity)</td>
        <td>
            @using (Html.BeginForm("Delete", "AdminCharity"))
            {
                @Html.Hidden("CharityId", item.CharityId)
                <input type="submit" value="Delete" />
            }
            <!--Html.ActionLink("Edit", "Edit", new { id=item.CharityId }) |
            Html.ActionLink("Details", "Details", new { id=item.CharityId }) |
            Html.ActionLink("Delete", "Delete", new { id=item.CharityId })-->
        </td>
    </tr>
}

</table>
<p>@Html.ActionLink("Add a new Charity", "Create")</p>