Capstone/Capstone.WebUI/Controllers/AdminPartnershipNightController.cs
using Capstone.Domain.Concrete;
using Capstone.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Capstone.WebUI.Models;

namespace Capstone.WebUI.Controllers
{
    public class AdminPartnershipNightController : Controller
    {
        //
        // GET: /AdminPartnershipNight/
        PartnershipNightRepository pnRepo;
        CharityRepository charRepo; 
        BvLocationRepository bvlocRepo;
        
        public AdminPartnershipNightController()
        {
            pnRepo = new PartnershipNightRepository();
            charRepo = new CharityRepository();
            bvlocRepo = new BvLocationRepository();
        }

        public ActionResult Index()
        {
            List<PartnershipNight> pnightEvents = pnRepo.GetPartnershipNights().ToList<PartnershipNight>();
            
            return View(pnightEvents);
        }

        public ViewResult Create()
        {
            return View("Edit", new PNightEditViewModel());
        }

        public ActionResult Edit(int partnershipNightId)
        {
            // Get the correct partnership night, and create a view model to store values in
            PartnershipNight pnight = pnRepo.GetPartnershipNights().FirstOrDefault(pn => pn.PartnershipNightId == partnershipNightId);
            PNightEditViewModel vmodel = new PNightEditViewModel();

            //Set view model to corresponding partnership night values
            vmodel.PartnershipNightId = pnight.PartnershipNightId;
            vmodel.Date = pnight.Date;
            vmodel.CharityId = pnight.Charity.CharityId;
            vmodel.BVLocationId = pnight.BVLocation.BvLocationId;
            vmodel.CheckRequestId = pnight.CheckRequestId;
            vmodel.Comments = pnight.Comments;
            vmodel.CheckRequestFinished = pnight.CheckRequestFinished;
            vmodel.BeforeTheEventFinished = pnight.BeforeTheEventFinished;
            vmodel.AfterTheEventFinished = pnight.AfterTheEventFinished;

            //Set List variables to contain lists of child objects for selection in the view
            vmodel.Charities = charRepo.GetCharities().ToList<Charity>();
            vmodel.Locations = bvlocRepo.GetBvLocations().ToList<BvLocation>();

            //Set session variables to contain lists of child objects for selection in the view
            //Session["charities"] = charRepo.GetCharities().ToList<Charity>();
            //Session["bvlocations"] = bvlocRepo.GetBvLocations().ToList<BvLocation>();

            return View(vmodel);
        }

        [HttpPost]
        public ActionResult Edit(PNightEditViewModel vmodel)
        {
            //PartnershipNight pnight = pnRepo.GetPartnershipNights().FirstOrDefault<PartnershipNight>(pn => pn.PartnershipNightId)

            if (ModelState.IsValid)
            {
                // Transfer view model values to a partnership night object
                PartnershipNight pnight = new PartnershipNight();
                pnight.PartnershipNightId = vmodel.PartnershipNightId;
                pnight.Date = vmodel.Date;
                pnight.Comments = vmodel.Comments;
                pnight.CheckRequestId = vmodel.CheckRequestId;
                pnight.CheckRequestFinished = vmodel.CheckRequestFinished;
                pnight.BeforeTheEventFinished = vmodel.BeforeTheEventFinished;
                pnight.AfterTheEventFinished = vmodel.AfterTheEventFinished;

                // Store the correct child objects 
                pnight.Charity = charRepo.GetCharities().FirstOrDefault(ch => ch.CharityId == vmodel.CharityId);
                pnight.BVLocation = bvlocRepo.GetBvLocations().FirstOrDefault(bvl => bvl.BvLocationId == vmodel.BVLocationId);
                
                // Save the changes to the partnership night 
                pnRepo.UpdatePartnershipNight(pnight);
                TempData["message"] = string.Format("Partnership Night for BV Location {0}, {1} has been saved", pnight.Date.ToShortDateString(), pnight.BVLocation.BvStoreNum);
                return RedirectToAction("Index");
            }
            else
            {
                // there is something wrong with the data values
                return View(vmodel);
            }
        }

        [HttpPost]
        public ActionResult Delete(int pnightId)
        {
            PartnershipNight deletedPNight = pnRepo.DeletePartnershipNight(pnightId);
            if (deletedPNight != null)
            {
                TempData["message"] = string.Format("Event on {0} was deleted",
                deletedPNight.Date.ToShortDateString());
            }
            return RedirectToAction("Index");
        }
    }
}

Capstone/Capstone.WebUI/Views/AdminPartnershipNight/Edit.cshtml
@model Capstone.WebUI.Models.PNightEditViewModel
@using Capstone.Domain.Entities;
@{
    ViewBag.Title = "Edit";
}

<h1>Edit Event </h1>
<h2>Date: @Model.Date.ToShortDateString()<br /> </h2>
<!-- Commenting out but add these back in when I have time to match the list item names to the id: Charity: Model.Charity.Name <br /> Store#: Model.BVLocation.BvStoreNum -->

@using (Html.BeginForm("Edit", "AdminPartnershipNight")) {

    <p>@Html.EditorFor(m => m.Date)</p>
    <p>@Html.EditorFor(m => m.CheckRequestId)</p>
    <p>@Html.EditorFor(m => m.Comments)</p>
    <p>@Html.EditorFor(m => m.CheckRequestFinished)</p>
    <p>@Html.EditorFor(m => m.BeforeTheEventFinished)</p>
    <p>@Html.EditorFor(m => m.AfterTheEventFinished)</p>

<table> <!--NOTE: Used in-line css in lieu of global css fixes -->
    <tr>
        <th style="text-align:left;">Charity</th>
    </tr>
    <tr>
        <td>
            @if(Model.Charities != null){ 
                @Html.DropDownListFor(m => m.CharityId, new SelectList(Model.Charities, "CharityId", "Name"));
                @Html.HiddenFor(x => x.CharityId)
            }
        </td>
    </tr>
    <tr>
        <th style="text-align:left;">BV Location</th>
    </tr>
    <tr>
        <td>
            @if(Model.Locations != null){
                @Html.DropDownListFor(m => m.BVLocationId, new SelectList(Model.Locations, "BvLocationId", "BvStoreNum"));
                @Html.HiddenFor(x => x.BVLocationId) 
            }
        </td>
   </tr>
</table>
    <br />
        <input type="submit" value="Save" />
@Html.ActionLink("Cancel and return to List", "Index")
}

Capstone/Capstone.WebUI/Views/AdminPartnershipNight/Index.cshtml
@model IEnumerable<Capstone.Domain.Entities.PartnershipNight>
@using System.Web.Mvc.Html

@{
    ViewBag.Title = "Partnership Nights";
}

<h2>All Partnership Nights</h2>
<table>
    <tr>
        <th>Date</th>
        <th>Store #</th>
        <th>Charity</th>
        <th>Chk Req Id</th>
        <th>Comments</th>
        <th>Chk Req Finished</th>
        <th>Pre-Event Form</th>
        <th>Post-Event Form</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>@Html.ActionLink(item.Date.ToShortDateString(), "Edit", new { item.PartnershipNightId })</td>
        <td>@item.BVLocation.BvStoreNum</td>
        <td>@item.Charity.Name</td>
        <td>@item.CheckRequestId <!-- Html.DisplayFor(modelItem => item.CheckRequestId)--></td>
        <td>@item.Comments <!--Html.DisplayFor(modelItem => item.Comments)--></td>
        <td>@item.CheckRequestFinished <!--Html.DisplayFor(modelItem => item.CheckRequestFinished)--></td>
        <td>@item.BeforeTheEventFinished <!--Html.DisplayFor(modelItem => item.BeforeTheEventFinished)--></td>
        <td>@item.AfterTheEventFinished <!--Html.DisplayFor(modelItem => item.AfterTheEventFinished)--></td>
        <td>@using(Html.BeginForm("Delete", "AdminPartnershipNight")){
                @Html.Hidden("PartnershipNightId", item.PartnershipNightId)
             <input type="submit" value="Delete" />
         }
            <!--Html.ActionLink("Edit", "Edit", new { id=item.PartnershipNightId }) |
            Html.ActionLink("Details", "Details", new { id=item.PartnershipNightId }) |
            Html.ActionLink("Delete", "Delete", new { id=item.PartnershipNightId }) -->
        </td>
    </tr>
}
</table>
<p>@Html.ActionLink("Add a new Partnership Night", "Create")</p>